name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Push Docker Images
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
      run: |
        cd Node
        docker build -t DOCKER_USERNAME/node1.4:latest .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push DOCKER_USERNAME/node1.4:latest

       
    - name: Debug Information
      run: |
        echo "DOCKER_USERNAME: $DOCKER_USERNAME"
        echo "DOCKER_PASSWORD: $DOCKER_PASSWORD"
        echo "docker build -t yourdockerhubusername/node-app:latest ."
        echo "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        echo "docker push yourdockerhubusername/node-app:latest"
        
        # Add more debugging information as needed
